//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.Squirrel.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.Squirrel.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squirrel example.
        /// </summary>
        internal static string Orc_Squirrel_Example_MainViewModel_Title {
            get {
                return ResourceManager.GetString("Orc_Squirrel_Example_MainViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string Orc_Squirrel_Example_MainWindow_CheckForUpdates {
            get {
                return ResourceManager.GetString("Orc_Squirrel_Example_MainWindow_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable directory (optional).
        /// </summary>
        internal static string Orc_Squirrel_Example_MainWindow_ExecutableDirectoryOptional {
            get {
                return ResourceManager.GetString("Orc_Squirrel_Example_MainWindow_ExecutableDirectoryOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show installation window.
        /// </summary>
        internal static string Orc_Squirrel_Example_MainWindow_ShowInstallationWindow {
            get {
                return ResourceManager.GetString("Orc_Squirrel_Example_MainWindow_ShowInstallationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Orc_Squirrel_Example_MainWindow_Update {
            get {
                return ResourceManager.GetString("Orc_Squirrel_Example_MainWindow_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update url.
        /// </summary>
        internal static string Orc_Squirrel_Example_MainWindow_UpdateUrl {
            get {
                return ResourceManager.GetString("Orc_Squirrel_Example_MainWindow_UpdateUrl", resourceCulture);
            }
        }
    }
}
